// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuCHv0pfDZGHID_FSrk1PH1x7hU20LYVA',
    appId: '1:812102753049:web:be6195b425fc6346650388',
    messagingSenderId: '812102753049',
    projectId: 'minicrm-91aa3',
    authDomain: 'minicrm-91aa3.firebaseapp.com',
    storageBucket: 'minicrm-91aa3.firebasestorage.app',
    measurementId: 'G-8L70S0PECE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDWdjaG9CJvRH-ZhyFWq6-dPPQYL5CdgE',
    appId: '1:812102753049:android:9be1c531bbab2e25650388',
    messagingSenderId: '812102753049',
    projectId: 'minicrm-91aa3',
    storageBucket: 'minicrm-91aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8wevFicqR8LlzFJSp2vhowV7gnT-1Nv0',
    appId: '1:812102753049:ios:89b369412cf99d0c650388',
    messagingSenderId: '812102753049',
    projectId: 'minicrm-91aa3',
    storageBucket: 'minicrm-91aa3.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrmViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8wevFicqR8LlzFJSp2vhowV7gnT-1Nv0',
    appId: '1:812102753049:ios:89b369412cf99d0c650388',
    messagingSenderId: '812102753049',
    projectId: 'minicrm-91aa3',
    storageBucket: 'minicrm-91aa3.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrmViewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuCHv0pfDZGHID_FSrk1PH1x7hU20LYVA',
    appId: '1:812102753049:web:cc165306d5d48efe650388',
    messagingSenderId: '812102753049',
    projectId: 'minicrm-91aa3',
    authDomain: 'minicrm-91aa3.firebaseapp.com',
    storageBucket: 'minicrm-91aa3.firebasestorage.app',
    measurementId: 'G-7DPWMR6GEZ',
  );
}
